# Generated by Django 5.0.6 on 2024-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_pago_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('id_productos', models.CharField(max_length=200)),
                ('precio_total', models.IntegerField()),
            ],
        ),
    ]
